#!/bin/sh

[ $(pamixer --get-mute) = true ] && echo 🔇 && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="Vol "
elif [ "$vol" -lt "30" ]; then
	icon="Vol "
else
	icon="Vol "
fi

echo "$icon$vol%"
